spring.application.name=e-food-authentication-service
server.port=8002
spring.profiles.active=dev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}

cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.access.key=${CLOUDINARY_ACCESS_KEY}
cloudinary.access.secret=${CLOUDINARY_ACCESS_SECRET}
folder.name.PROFILE_PHOTO_IMAGE_FOLDER=${PROFILE_PICTURE_FOLDER}
springdoc.swagger-ui.url=/v3/api-docs
